spring:
  datasource:
    url: jdbc:mysql://localhost:3306/payment_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: n3u3da!
  sql:
    init:
      mode: always
      schema-locations: classpath:schema-mysql.sql
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080





